### ISSUE TITLE
Questions about the code

### ISSUE THREAD

**Issue by auszone** [vert-x3/vertx-hawkular-metrics#32]
Why wrap the piece of code (creating a http client) in a context?
https://github.com/vert-x3/vertx-hawkular-metrics/blob/master/src/main/java/io/vertx/ext/hawkular/impl/Sender.java#L115-L122
@tsegismont

**Comment by auszone** [comment]
Is that an optimization that reduce idle http connections?

**Comment by tsegismont** [comment]
No, it's because we want to create the HttpClient instance on the right
execution context. The same context which is used throughout the SPI
implementation to collect metrics, add them to te buffer. And here, send
them to Hawkular with an HttpClient. See this doc for detailed info:
https://github.com/vietj/vertx-materials/blob/master/src/main/asciidoc/Demystifying_the_event_loop.adoc

2016-05-29 7:01 GMT+02:00 Austin Kuo <notifications@github.com>:
